name = "DiscretePersistentHomologyTransform"
uuid = "9598d6b2-89d7-11ea-0bed-b1104e2053b2"
keywords = ["topological data analysis", "persistent homology transfer"]
license = "MIT"
desc = "Discrete persistent homology transfer calculations"
author = "Yossi Bokor <yossi.bokor@anu.edu.au>"
version = "1.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Eirene = "9c0f25c4-2ca1-5870-89f6-52640788da1d"
Hungarian = "e91730f6-4275-51fb-a7a0-7064cfbd3b39"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CSV = "0.5.16, 0.6"
DataFrames = "0.20.0, 0.21"
Eirene = "1"
Hungarian = "^0"
SparseArrays = "^1"
julia = "1"
